[tox]
envlist = 
    py{309}
skip_missing_interpreters =
    true

# Define the minimal tox version required to run;
# if the host tox is less than this the tool with create an environment and
# provision it with a tox that satisfies it under provision_tox_env.
# At least this version is needed for PEP 517/518 support.
minversion = 4.3.0

# Activate isolated build environment. tox will use a virtual environment
# to build a source distribution from the source tree. For build tools and
# arguments use the pyproject.toml file as specified in PEP-517 and PEP-518.
isolated_build = true

[testenv]
deps =
    pip-tools
    -rrequirements.txt
setenv =
    PIP_NO_INDEX = false
    PYTHONPATH = {toxinidir}/src
install_command = 
    pip --disable-pip-version-check install {opts} {packages} 
commands =
    python --version
    pip-compile requirements.in requirements.dev.in -o requirements.txt
    pytest -v -s 

[testenv:pip-compile]
description = run pip-compile for project
allowlist_externals = 
    .\.tox\pip-compile\*
; Run this to `pip-compile` your `requirements*.in` files into 
; `requirements.txt`. Note that this will use your default version of python 
; when doing dependency resolution, even though there are four other 
; environments in `envlist` above.
deps=
    # Note that we require `pip-tools` here, *not* in a `requirements.*` file.
    pip-tools
setenv =
    PIP_NO_INDEX = false
install_command = 
    pip --disable-pip-version-check install {opts} {packages}
commands=
    pip-compile requirements.in requirements.dev.in -o requirements.txt

[testenv:push]
description = run build for project to create a distribution archive and \
    pushes it to the local python repository. Make sure that the python \
    repository is running and that you have increased the version tag.
allowlist_externals = 
    .\.tox\build\*
    py
deps = 
    build
    fire
    toml
setenv =
    PIP_INDEX_URL = http://localhost:8080
    PIP_NO_INDEX = false
install_command = 
    pip --disable-pip-version-check install {opts} {packages} \
        --index-url=http://localhost:8080
commands = 
    py -m build
    python .\scripts\version.py push
    python .\scripts\version.py remove-dist

[testenv:get-version]
description = returns package version number
skip_install = True
skipsdist = True
allowlist_externals =
    *.\scripts\version.py
deps =
    fire
    toml
setenv =
    PIP_INDEX_URL = http://localhost:8080
    PIP_NO_INDEX = false
install_command = 
    pip --disable-pip-version-check install {opts} {packages} \
        --index-url=http://localhost:8080
commands =
    python .\scripts\version.py get --with-pre-release-placeholder

[testenv:patch]
description = Increases patch tag of the Python package
skip_install = True
skipsdist = True
allowlist_externals =
    *.\scripts\version.py
deps =
    fire
    toml
setenv =
    PIP_INDEX_URL = http://localhost:8080
    PIP_NO_INDEX = false
install_command = 
    pip --disable-pip-version-check install {opts} {packages} \
        --index-url=http://localhost:8080
commands =
    python .\scripts\version.py patch

[testenv:minor]
description = Increases minor tag of the Python package
skip_install = True
skipsdist = True
allowlist_externals =
    *.\scripts\version.py
deps =
    fire
    toml
setenv =
    PIP_INDEX_URL = http://localhost:8080
    PIP_NO_INDEX = false
install_command = 
    pip --disable-pip-version-check install {opts} {packages} \
        --index-url=http://localhost:8080
commands =
    python .\scripts\version.py minor

[testenv:major]
description = Increases major tag of the Python package
skip_install = True
skipsdist = True
allowlist_externals =
    *.\scripts\version.py
deps =
    fire
    toml
setenv =
    PIP_INDEX_URL = http://localhost:8080
    PIP_NO_INDEX = false
install_command = 
    pip --disable-pip-version-check install {opts} {packages} \
        --index-url=http://localhost:8080
commands =
    python .\scripts\version.py major